@host = http://localhost:3001
@token = # JWT token from login response



### User Registration
POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "newuser3",
    "email": "newuser3@example.com",
    "password": "password123"
}



### User Login
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "newuser3@example.com",
    "password": "password123"
}



### Create Journal Entry
POST {{host}}/api/journal
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "My Journal Entry",
    "content": "Today I learned about huehue."
}



### Get All Journal Entries
GET {{host}}/api/journal
Authorization: Bearer {{token}}



### Get Journal Entry by ID
# Replace ':id' with an actual entry ID
GET {{host}}/api/journal/:id
Authorization: Bearer {{token}}



### Update Journal Entry
# Replace ':id' with an actual entry ID
PUT {{host}}/api/journal/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Updated Journal Entry",
    "content": "Today I explored more about Node.js."
}



### Delete Journal Entry
# Replace ':id' with an actual entry ID
DELETE {{host}}/api/journal/:id
Authorization: Bearer {{token}}


